---
- name: "Playbook to Update application"
  hosts: "{{ target_host }}"
  become: yes
  vars:
    - status : "present"
    - key : "~/.ssh/id_rsa.pub"

  tasks:
  - name: "Copy the authorized key file from"
    authorized_key:
      user: ubuntu
      state: present
      key: "{{ lookup('file', '{{ key }}')}}"
  - name: "Updating Server"
    copy:
      src: "{{ playbook_dir }}/index.html"
      dest: /var/www/html/
      
